### PR TITLE
Prepare 0.0.1.dev16 release

### PR DESCRIPTION
**Pull request by descent3me**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:
@spotify/alf 

**Release note**:

```release-note
Prepare 0.0.1.dev16 release.
```

### CODE REVIEW

**Comment by ocsw** [comment]
Should this include deletions?

**Comment by descent3me** [comment]
Err its ridiculous that this doesn't sort by merge date: https://github.com/spotify/gordon-gcp/pulls?q=is%3Apr+is%3Aclosed

 I thought that was in a previous release

**Comment by ocsw** [comment]
I just looked at the list of commits in develop.

**Comment by descent3me** [comment]
Maybe this repo is setup different.  The last one I looked at commits were ordered by creation date, which also didn't help.

**Comment by ocsw** [comment]
I dunno, the link you posted lists by PR _number_, which has nothing to do with actual merge date.

**Comment by ocsw** [comment]
+1

**Comment by descent3me** [comment]
Yeah, I was hoping since the commit order was useless, that PR order would be sorted my merge date, but its stupidly sorted by PR number.

**Comment by ocsw** [comment]
Isn't the commit order in develop logical?

**Pull request merged**
