### PR TITLE
Dedupe instances by IP

### PR DESCRIPTION
**Pull request by ocsw**
**What this PR does / why we need it**:
Google can return both an instance that is in the middle of being deleted and one that is being created, with the same IP, so we need to dedupe them.

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixed Google duplicate-IP problem.
```

### CODE REVIEW

**Comment by ocsw** [comment]
@spotify/alf PTAL, duplicate IP problem

**Comment by ocsw** [comment]
@gordon/alf applied Will's suggestions, PTAL

**Comment by descent3me** [comment]
Is it insufficient to filter on the status of the instance when janitor talks to the GCE API?

**Comment by descent3me** [comment]
Wouldn't the status be set to TERMINATED?

https://cloud.google.com/compute/docs/reference/rest/v1/instances/aggregatedList

**Comment by ocsw** [comment]
It's also set to terminated when you stop an instance but don't delete it.  https://cloud.google.com/compute/docs/instances/stopping-or-deleting-an-instance

**Comment by descent3me** [comment]
We probably don't want records for stopped instances either, right?

**Comment by ocsw** [comment]
I think we do.  What if you take a box down for a few minutes and then bring it back up?  I don't think you want to wait 15+ minutes for it to reappear.

**Comment by ocsw** [comment]
Also, I don't actually know currently what the statuses are and if they're actually logical.  We already know Google isn't really Doing The Right Thing in one way, I'm not sure I want to trust them in two.

**Comment by ocsw** [comment]
How's this for an idea?  I just added logging.  We can run it for a while and see what the conflicts actually look like.  If they consistently have one instance in TERMINATED, we can junk this code and filter by status in the original query.

**Pull request closed without merging**
