### PR TITLE
Add deletion to the janitor reconciler

### PR DESCRIPTION
**Pull request by ocsw**
**What this PR does / why we need it**:
This adds deletions to the janitor's reconciler.

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Added deletions to the janitor reconciler
```

### CODE REVIEW

**Comment by ocsw** [comment]
@spotify/alf ok?

**Comment by descent3me** [comment]
I think it is worth discussing that this will now make Gordon remove records if an attempt to list instances in a project fails for some reason (w.r.t. what @econchick was saying this morning).  Do we have a plan to work around that?

**Comment by descent3me** [comment]
(otherwise changes lgtm)

**Comment by ocsw** [comment]
Not yet, but I'm going to add that to my list.

**Comment by descent3me** [comment]
@ocsw [Here is the PR](https://github.com/spotify/gordon-gcp/pull/61) (specifically [this diff](https://github.com/spotify/gordon-gcp/pull/61/files#diff-083b411d0604963958532d9873032024R149)) that I felt would make it safe to merge this PR, if you have time to review.  It might have the downside of making Janitor fail all the time, so will probably require more work later, but for the time being it would at least ensure we're not deleting valid records.

**Comment by ocsw** [comment]
rebased with that PR

**Pull request merged**
