### PR TITLE
make keyfile optional

### PR DESCRIPTION
**Pull request by reneweb**
**What this PR does / why we need it**:
The GAuthClient can now work with default credentials, so it is not required to have the keyfile provided anymore.

### CODE REVIEW

**Comment by ocsw** [comment]
LGTM, although I don't know if there have been any discussions.

**Comment by descent3me** [comment]
@reneweb docs need to be updated as well

**Comment by reneweb** [comment]
@descent3me You mean marking the keyfile in those examples as optional https://github.com/spotify/gordon-gcp/blob/43935bf6ecda74e8a333adad19beac250b167242/src/gordon_gcp/plugins/janitor/gpubsub_publisher.py#L41 right?

**Comment by descent3me** [comment]
@reneweb yep!

**Pull request merged**
