### PR TITLE
Limit output of validation errors

### PR DESCRIPTION
**Pull request by descent3me**
**What this PR does / why we need it**:
Reduces output of validation errors. Because of how we do validation against an array of schemas, these validation errors occur on receipt of every event message. 

This PR changes the output from: 

```
2018-09-20T16:40:57.725Z gordon[1]: Given message was not valid against the schema "audit-log"
Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.6/site-packages/gordon_gcp/schema/validate.py", line 127, in validate
    jsonschema.validate(message, self.schemas[schema_name])
  File "/usr/src/app/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/src/app/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'protoPayload' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'description': 'Schema for parsing Google Audit Log Messages',
     'id': 'https://github.com/spotify/gordon-gcp/blob/master/gordon_gcp/schemas/audit-log.schema.json',
     'properties': {'logName': {'description': 'Name of audit log',
                                'examples': ['projects/a-project-id/logs/cloudaudit.googleapis.com%2Factivity'],
                                'pattern': '^projects/[a-z][a-z\\-0-9]{5,29}/logs/cloudaudit.googleapis.com%2Factivity',
                                'type': 'string'},
                    'protoPayload': {'properties': {'methodName': {'description': 'Action '
                                                                                  'performed '
                                                                                  'on '
                                                                                  'a '
                                                                                  'GCP',
                                                                   'enum': ['v1.compute.instances.insert',
                                                                            'v1.compute.instances.delete'],
                                                                   'type': 'string'},
                                                    'resourceName': {'description': '',
                                                                     'examples': ['projects/a-project-id/zones/a-zone-name/instances/an-instance-name'],
                                                                     'pattern': '^projects/[0-9]+/zones/[a-z\\-0-9]+/instances/[a-z\\-0-9]+',
                                                                     'type': 'string'}},
                                     'required': ['methodName',
                                                  'resourceName'],
                                     'type': 'object'},
                    'receiveTimestamp': {'description': 'Time the log '
                                                        'entry was '
                                                        'received by '
                                                        'Stackdriver '
                                                        'Logging',
                                         'examples': ['2018-01-01T23:13:45.123456789Z'],
                                         'type': 'string'},
                    'timestamp': {'description': 'Time the operation '
                                                 'status was reported',
                                  'examples': ['2018-01-01T23:13:45.123456789Z'],
                                  'type': 'string'}},
     'required': ['protoPayload', 'logName'],
     'title': 'Google Audit Log Messages',
     'type': 'object'}

On instance:
    {'action': 'deletions',
     'resourceRecords': {'name': '<SOME_NAME>',
                         'rrdatas': ['<SOME_OTHER_NAME>'],
                         'ttl': 300,
                         'type': 'CNAME'},
     'timestamp': '2018-09-20T16:38:11.000000000Z'}
```

to

```
ERROR:root:Given message was not valid against the schema "audit-log": 'protoPayload' is a required property
```

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:
@spotify/alf 

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ocsw** [comment]
Should we collect these across the schema validations and only output them if none of the schemas match?

**Comment by descent3me** [comment]
We are losing 1) the name of the error, which I think is superfluous given the error message, 2) the printout of the schema, which we already have in the repo, and 3) the printout of the incoming message, which we already log when the message is received (like below). 

```
 2018-09-21T18:44:26.026Z gordon[1]: [msg-210539333583261]: Received data: {'action': 'deletions', 'resourceRecords': {'name': '<SOME_NAME>', 'rrdatas': ['<SOME_OTHER_NAME>'], 'ttl': 300,  'type': 'CNAME'}
```

We do output if no schema matches here: https://github.com/spotify/gordon-gcp/blob/develop/src/gordon_gcp/plugins/service/event_consumer.py#L341

**Comment by ocsw** [comment]
No, I mean I agree with the change, I'm just wondering if we can go even further.

**Comment by descent3me** [comment]
Aha, I missed the "only" in your question @ocsw. That's not a bad idea, but it is a larger effort, to do a little more refactoring to move the error logging around.  I'm disinclined to put the time to do that right now, but I can if you think it's important enough.

I also don't know what's causing the docs build to fail, or how to debug or retrigger even.

**Comment by ocsw** [comment]
Yeah, maybe something for v2.
+1

**Pull request merged**
